package synechron.emps;

import synechron.emps.service.EmployeeService;

/*
This main package is called the 'base' package
 */
public class Main {
    public static void main(String[] args) {
        // TODO Autogenerated method sub

        EmployeeService employeeService =  EmployeeService.getInstance();
    }
}